apiVersion: v1
kind: Service
metadata:
  name: confluent-cloud-spring-kafka-sample-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: confluent-cloud-spring-kafka-sample
  type: LoadBalancer

