spring:
  kafka:
    properties:
      sasl:
        jaas:
          config: ${SASL_JAAS_CONFIG}
        mechanism: PLAIN
      security:
        protocol: SASL_SSL
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: ${BOOTSTRAP_SERVERS}

